services:
  - type: web
    name: document-system
    env: docker
    region: frankfurt
    plan: free
    branch: main
    repo: https://github.com/Emzy123/documentation_system.git
    envVars:
      - key: APP_NAME
        value: StudentDocs
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: document-db
          property: connectionString
      - key: APP_KEY
        generateValue: true
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120

databases:
  - name: document-db
    databaseName: document_system
    user: laravel
    plan: free
    region: frankfurt
